# Generated by Django 2.2.1 on 2019-05-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0002_auto_20190523_1928'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
            ],
        ),
    ]
